import enum


class DomainEvents(str, enum.Enum):
    SIMULATION_STATUS = "SIMULATION_STATUS"
    OUTPUT_SAVED = "OUTPUT_SAVED"
    SIMULATION_FINISHED = "SIMULATION_FINISHED"
    SIMULATION_STOPPED = "SIMULATION_STOPPED"
    SIMULATION_PAUSED = "SIMULATION_PAUSED"
