from core.entity.core import Entity, EntityProperties, EntityManager


class GeneratedEntity(Entity):
    """Entities generated by an entity emitter."""

    _properties: EntityProperties
    """Properties of the entity."""

    def __init__(self, name: str, properties: EntityProperties, entity_manager: EntityManager = None):
        """Creates a generated entity"""
        super().__init__(name, entity_manager)
        self._properties = properties

    def get_properties(self) -> EntityProperties:
        """Lists the properties of the entity"""
        return self._properties
